- hosts: localhost
  connection: local

  vars:
    region: eu-west-1
    ami: ami-4b1c763c
  
  tasks:
    - debug: msg="{{ token | regex_replace('^https?:\\/\\/[\\w\\.]*\\/([\\w]*)$', '\\1') }}"
      register:  cp
    
    - name: Set up fleet security group
      ec2_group:
        region: "{{region}}"
        name: fleet_sg
        description: Fleet secutiy group
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 172.31.0.0/16
        rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      register: fleet_group

    - name: Provision m3.medium instances
      ec2:
        region: "{{region}}"
        group: fleet_sg
        image: "{{ami}}"
        instance_type: m3.medium
        wait: true
        exact_count: 4
        user_data: "{{ lookup('template', 'userdata/default_instance_user_data.yaml') }}"
        volumes:
          - device_name: /dev/xvda
            volume_size: 20
        count_tag:
          Name: "{{cp.msg}}_fleet_default"
        instance_tags:
          Name: "{{cp.msg}}_fleet_default"
      register: ec2_small

    - debug: msg="ec2_small ips {{ item.public_ip }}"
      with_items: "{{ ec2_small.tagged_instances }}"

    - name: Provision m3.medium persistent instance
      ec2:
        region: "{{region}}"
        group: fleet_sg
        image: "{{ami}}"
        instance_type: m3.medium
        wait: true
        exact_count: 3
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data.yaml') }}"
        volumes:
          - device_name: /dev/xvda
            volume_size: 20
          - device_name: /dev/xvdf
            volume_size: 50
        count_tag:
          Name: "{{cp.msg}}_fleet_persistent"
        instance_tags:
          Name: "{{cp.msg}}_fleet_persistent"
      register: ec2_persistent

    - debug: msg="ec2_persistent ips {{ item.public_ip }}"
      with_items: "{{ ec2_persistent.tagged_instances }}"

    - name: Monitoring host
      ec2:
        region: "{{region}}"
        group: fleet_sg
        image: "{{ami}}"
        instance_type: m3.medium
        wait: true
        exact_count: 1
        user_data: "{{ lookup('template', 'userdata/monitor_instance_user_data.yaml') }}"
        volumes:
          - device_name: /dev/xvda
            volume_size: 20
        count_tag:
          Name: "{{cp.msg}}_fleet_monitor"
        instance_tags:
          Name: "{{cp.msg}}_fleet_monitor"
      register: ec2_monitor

    - debug: msg="ec2_monitor ips {{ item.public_ip }}"
      with_items: "{{ ec2_monitor.tagged_instances }}"

