- hosts: localhost
  connection: local

  vars:
    region: eu-west-1
    az: b
    ami: ami-eb97bc9c #eu-west-1 HMV 766.4.0 (stable)
    #ami: ami-c3cae3b4 #eu-west-1 HMV CoreOS 815.0.0 (alpha)
    env: p
    ipcode: P295
    systemCode: "CoreOS-Universal-Publishing"
    description: "CoreOS-Universal-Publishing"
    teamDL: "george.angel@ft.com"
    environment_tag: default
  vars_files:
    - keys.yaml

  tasks:
    - debug: msg="{{ token | regex_replace('^https?:\\/\\/[\\w\\.]*\\/([\\w]{8})[\\w]*$', '\\1') }}"
      register:  cp

    - ec2_vpc:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        state: present
        cidr_block: 172.23.0.0/16
        resource_tags: {"Name": "coreos", "env": "p", "ipcode": "P295", "systemCode": "CoreOS", "description": "CoreOS", "teamDL": "george.angel@ft.com}"}
        subnets:
          - cidr: 172.23.0.0/16
            az:  "{{ region }}{{az}}"
            resource_tags: {"Name": "coreos", "env": "p", "ipcode": "P295", "systemCode": "CoreOS", "description": "CoreOS", "teamDL": "george.angel@ft.com}"}
        internet_gateway: True
        route_tables:
          - subnets:
              - 172.23.0.0/16
            routes:
              - dest: 0.0.0.0/0
                gw: igw
      register: vpc

    - debug: msg="VPC {{ vpc }}"

    - name: Set up fleet security group
      ec2_group:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        name: "coreos-up-{{ cp.msg }}"
        description: Fleet security group
        vpc_id: "{{ vpc.vpc_id }}"
        rules:
          # OSB + LDNWebPerf
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 82.136.1.214/32
          # XP - Cluj office
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 194.117.242.0/24
          # aws - jumpbox
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 52.16.117.250/32
          # aws - jumpbox fleet API
          - proto: tcp
            from_port: 49153
            to_port: 49153
            cidr_ip: 52.16.117.250/32
          # Allow 80 from everywhere
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          # Allow 443 from everywhere
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          # Allow internal requests
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 172.23.0.0/16
        rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
          # Allow timesync/ntp out
          - proto: udp
            from_port: 123
            to_port: 123
            cidr_ip: 0.0.0.0/0
      register: fleet_group

    - name: Tag UP CoreOS security group
      ec2_tag:
        resource: "{{fleet_group.group_id}}"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        state: present
        tags:
          Name: "coreos-up-{{ cp.msg }}"
          env: "{{env}}"
          ipcode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          coco-environment-tag: "{{environment_tag}}"

    - name: cluster-elb
      ec2_elb_lb:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        name: "coreos-up-{{cp.msg}}"
        state: present
        security_group_ids: '{{fleet_group.group_id}}'
        subnets:
          - "{{ vpc.subnets[0].id }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 8080
        purge_listeners: True
        health_check:
          ping_protocol: tcp # options are http, https, ssl, tcp
          ping_port: 8080
          #ping_path: "/index.html" # not required for tcp or ssl
          response_timeout: 5 # seconds
          interval: 30 # seconds
          unhealthy_threshold: 2
          healthy_threshold: 10
      register: cluster_elb

    - name: tag ELB
      shell: ". /.venv/bin/activate && aws --region {{region}} elb add-tags --load-balancer-names coreos-up-{{cp.msg}} --tags Key=Name,Value=coreos-up-{{cp.msg}} Key=env,Value={{env}} Key=ipcode,Value={{ipcode}} Key=systemCode,Value={{systemCode}} Key=description,Value={{description}} Key=teamDL,Value={{teamDL}} Key=coco-environment-tag,Value={{environment_tag}}"

    - debug: msg="cluster_elb dns {{ cluster_elb.elb.dns_name }}"

    - name: Provision m3.large instances
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{ cp.msg }}"
        image: "{{ami}}"
        instance_type: m3.large
        wait: true
        exact_count: 2
        user_data: "{{ lookup('template', 'userdata/default_instance_user_data.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 30
            delete_on_termination: true
        count_tag:
          Name: "ftstt{{cp.msg}}-caw1{{az}}-eu-p"
        instance_tags:
          Name: "ftstt{{cp.msg}}-caw1{{az}}-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"
      register: ec2_small

    - debug: msg="ec2_small ips {{ item.public_ip }}"
      with_items: "{{ ec2_small.tagged_instances }}"

    - name: Provision m3.large persistent instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{ cp.msg }}"
        image: "{{ami}}"
        instance_type: m3.large
        wait: true
        exact_count: 1
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data_1.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 30
            delete_on_termination: true
          - device_name: /dev/xvdf
            volume_size: 200
            delete_on_termination: true
        count_tag:
          Name: "ftpr1{{cp.msg}}-caw1{{az}}-eu-p"
        instance_tags:
          Name: "ftpr1{{cp.msg}}-caw1{{az}}-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"
      register: ec2_persistent

    - debug: msg="ec2_persistent ips {{ item.public_ip }}"
      with_items: "{{ ec2_persistent.tagged_instances }}"

    - name: Provision m3.large persistent instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{ cp.msg }}"
        image: "{{ami}}"
        instance_type: m3.large
        wait: true
        exact_count: 1
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data_2.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 30
            delete_on_termination: true
          - device_name: /dev/xvdf
            volume_size: 200
            delete_on_termination: true
        count_tag:
          Name: "ftpr2{{cp.msg}}-caw1{{az}}-eu-p"
        instance_tags:
          Name: "ftpr2{{cp.msg}}-caw1{{az}}-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"
      register: ec2_persistent

    - debug: msg="ec2_persistent ips {{ item.public_ip }}"
      with_items: "{{ ec2_persistent.tagged_instances }}"

    - name: Provision m3.large persistent instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{region}}"
        group: "coreos-up-{{ cp.msg }}"
        image: "{{ami}}"
        instance_type: m3.large
        wait: true
        exact_count: 1
        user_data: "{{ lookup('template', 'userdata/persistent_instance_user_data_3.yaml') }}"
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/xvda
            volume_size: 30
            delete_on_termination: true
          - device_name: /dev/xvdf
            volume_size: 200
            delete_on_termination: true
        count_tag:
          Name: "ftpr3{{cp.msg}}-caw1{{az}}-eu-p"
        instance_tags:
          Name: "ftpr3{{cp.msg}}-caw1{{az}}-eu-p"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{systemCode}}"
          description: "{{description}}"
          teamDL: "{{teamDL}}"
          stopSchedule: "nostop"
          coco-environment-tag: "{{environment_tag}}"
      register: ec2_persistent

    - debug: msg="ec2_persistent ips {{ item.public_ip }}"
      with_items: "{{ ec2_persistent.tagged_instances }}"

